global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'analystic-a-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8080']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
